function setCookie(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cname+"="+cvalue+";"+expires+";path=/";}
function getCookie(cname){var name=cname+"=";var decodedCookie=decodeURIComponent(document.cookie);var ca=decodedCookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1);}
if(c.indexOf(name)==0){return c.substring(name.length,c.length);}}
return"";}
function makeid(){var text="";var possible="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";for(var i=0;i<5;i++)
text+=possible.charAt(Math.floor(Math.random()*possible.length));return text;}
function validateEmail(email){var re=/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;var valid_=re.test(email);var form=$('.account-form form');form.find('.subtitle.medium').remove();if(valid_){}else{form.find('[name=email]').after('<p class="subtitle medium">Email not correct!</p>');return false;}
return true;}
var code_id=makeid();var payer=makeid();function saveLogForm(form){var type=$('.default-part.checkout-section').data('product');if($('.account-view input[name="account"]').length>0)
var link=$('.account-view input[name="account"]').val();else
var link=$('.account-change.main-account').data('account');var badLink='';if($('.bad-link').length>0)
badLink=1;var product_id=$('.content .package').data('product-id');$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'send_log_form_action','code':code_id+'_'+form,'link':link,'product_id':product_id,'type':type,'badLink':badLink,},success:function(data){}});}
function loader(key,container){if(key){$(container).css('position','relative');$(container).append('<div class="loader"><i class="fas fa-spinner fa-spin"></i></div>');}else{$(container+' .loader').remove();}}
function removePay(){if($('.default-part.payment').length>0){$('.default-part.payment').remove();}
if($('.account-change.account-photo').length>0){$('.account-change.account-photo').parent().remove();}
if($('.summary').length>0){$('.summary').remove();}}
function setPackage(packege){$('.package').data('package',packege);}
function saveLog(log){log=payer+': '+log;$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'save_log_action','log':log},success:function(data){}});}
function showPayBlock(account,product_id){var product=$('.checkout-section').data('product');var id_product=$('.package').data('product-id');var package=$('.package').data('package');var email=$('.account-change.main-account').data('email');var media='';var c_m=$('.media-item.active').length;var c=0;if(c_m>0){$('.media-item.active').each(function(){media+=$(this).data('url')+';';c++;if(c>=c_m){sendPayDataNew(id_product,account,product,package,email,media);}});}else{sendPayDataNew(id_product,account,product,package,email,media);}}
function sendPayDataNew(id_product,account,product,package,email,media){$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'get_payment_action','id_product':id_product,'account':account,'product':product,'package':package,'email':email,'media':media},success:function(data){if(data){$('.checkout-section').append(data);$([document.documentElement,document.body]).animate({scrollTop:$(".default-part.payment").offset().top},1000);}}});}
function showCheckedViews(account,product_id,type){saveLog('showCheckedViews | product-id '+product_id);saveLogForm('get_account_photo_action');$('.checkout-section').append('<div class="loader" style="position: relative;padding-top: 0px;"><i class="fas fa-spinner fa-spin"></i></div>');$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'get_account_photo_action','id_product':product_id,'account':account,'type':type},success:function(data){if(data){saveLogForm('get_account_photo_action');$('.default-part.checkout-section').append(data);loader(false,'.checkout-section');}}});}
function nextStep(){var product=$('.checkout-section').data('product');var account=$('.account-change.main-account').data('account');var account_id=$('.account-change.main-account').data('id');var product_id=$('.package').data('product-id');saveLog('nextStep | product-id '+product_id);if(account&&product_id){switch(product){case'followers':case'autolikes':showPayBlock(account,product_id);break;case'views':showCheckedViews(account_id,product_id,'video');break;case'likes':showCheckedViews(account_id,product_id,'image');break;}}}
function getCount(){var count=$('.checkout-section .media-item.active').length;return count;}
function getTotal(){var count=getCount();var packege=$('.package').data('package');return Math.ceil(packege/count);}
function reloadCart(){setTimeout(function(){var total=getTotal();$('.count-likes-set').text(total);},200);}
function doneAllCart(){var account=$('.account-change.main-account').data('account');var product_id=$('.package').data('product-id');showPayBlock(account,product_id);}
function addSummary(id_media){var product=$('.checkout-section').data('product');var img=$('.item-id-'+id_media+' img').attr('src');var block='<div class="summary-item summary-item-'+id_media+'">'+'<img src="'+img+'" alt="">'+'<p><span class="count-likes-set"></span> '+product+'</p>'+'<a href="#" onclick="removeSummary(\''+id_media+'\');return false;"><i class="far fa-times-circle"></i></a>'+'</div>';$('#summary-list').append(block);$('.summary').fadeIn(300);if($('.default-part.payment').length<1){var account=$('.account-change.main-account').data('account');var product_id=$('.package').data('product-id');}
reloadCart();}
function removeSummary(id_media){$('.summary-item-'+id_media).remove();$('.item-id-'+id_media).removeClass('active');reloadCart();if($('.checkout-section .media-item.active').length<1){$('.summary').fadeOut(300);if($('.default-part.payment').length>0){$('.default-part.payment').remove();}}}
function checkPaysData(paymentID,email,first_name,last_name,payer_id,status,actions){var product=$('.checkout-section').data('product');var account=$('.account-change.main-account').data('account');var product_id=$('.package').data('product-id');var packege=$('.package').data('package');var media='';saveLog('checkPaysData | product-id '+product_id);var c_m=$('.media-item.active').length;var c=0;if(c_m>0){$('.media-item.active').each(function(){media+=$(this).data('url')+';';c++;if(c>=c_m){sendPayData(paymentID,email,first_name,last_name,payer_id,status,product,account,product_id,packege,media,actions);}});}else{sendPayData(paymentID,email,first_name,last_name,payer_id,status,product,account,product_id,packege,media,actions);}}
function sendPayData(paymentID,email,first_name,last_name,payer_id,status,product,account,product_id,packege,media,actions){saveLog('sendPayData | product-id '+product_id);$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'set_payment_data_action','paymentID':paymentID,'email':email,'first_name':first_name,'last_name':last_name,'payer_id':payer_id,'status':status,'product':product,'account':account,'product_id':product_id,'packege':packege,'media':media},success:function(data){actions.redirect();}});}
$(document).ready(function(){$('img').each(function(e){var src=$(this).data('src');if(src)
$(this).attr('src',src);});if($('.account-view input[name="email"]').length>0){var email=getCookie('email');if(email)
$('.account-view input[name="email"]').val(email)}
if($('.account-view input[name="account"]').length>0){var account=getCookie('account');if(account)
$('.account-view input[name="account"]').val(account)}
$('.package').on('click','.select-new-package',function(e){e.preventDefault();removePay();$('.package').fadeOut(30);$('.package').data('product-id',false);$('.package-select').fadeIn(300);});$('.package-select .change-new-package').click(function(e){e.preventDefault();loader(true,'.package-select');var _this=$(this);var id_product=$('.package-select select').val();var product=_this.data('product');$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'get_package_action','id_product':id_product,'product':product,},success:function(data){if(data){$('.package').html(data);$('.package-select').fadeOut(30);$('.package').fadeIn(300);$('.package').data('product-id',id_product);saveLog('change-new-package | product-id '+id_product);nextStep();loader(false,'.package-select');}else{loader(false,'.package-select');}}});});$('.account-view').on('click','.select-account',function(e){e.preventDefault();loader(true,'.account-view');var _this=$(this);var account=$('.account-view input[name="account"]').val();var email=$('.account-view input[name="email"]').val();var product=$('.package').data('product-id');if(!account){loader(false,'.account-view');var form=$('.account-view');form.find('.subtitle.medium').remove();form.find('[name=account]').after('<p class="subtitle medium">Field not correct!</p>');return false;}
if(!validateEmail(email)){loader(false,'.account-view');return false;}
setCookie('email',email,365);setCookie('account',account,365);saveLogForm('get_account_action');$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'get_account_action','account':account,'email':email,'product':product,},success:function(data){if(data){saveLogForm('get_account_action');$('.account-view').html(data);}
loader(false,'.account-view');}});});$('.account-view').on('click','.account-change-btn',function(e){e.preventDefault();removePay();var _this=$(this);$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'change_account_action'},success:function(data){if(data){$('.account-view').html(data);}},});});$('.checkout-section').on('click','.load-more-media',function(e){e.preventDefault();loader(true,'.checkout-section');var maxId=$('.account-photo .media-cor').last().data('maxid');if(maxId){var account=$('.account-change.main-account').data('id');var product=$('.checkout-section').data('product');var type='image';if(product=='views')type='video';$.ajax({type:'POST',dataType:'html',url:'/wp-admin/admin-ajax.php',data:{'action':'get_account_photo_next_action','maxId':maxId,'account':account,'type':type},success:function(data){if(data){$('.account-change.account-photo .row').append(data);}
loader(false,'.checkout-section');},});}else{loader(false,'.checkout-section');}});$('.checkout-section').on('click','.media-item',function(e){e.preventDefault();var _this=$(this);var id=_this.data('id');var product=$('.checkout-section').data('product');if(_this.hasClass('active')){removeSummary(id);}else{var count=getCount();var total=getTotal();if(count>=10){alert('You can choose a maximum of 10 posts.');}else if(total<=100&&product=='views'){alert('Minimal amount 100 '+product+'. To enlarge, change the package.');}else if(total<=20&&product=='likes'){alert('Minimal amount 20 '+product+'. To enlarge, change the package.');}else{addSummary(id);_this.addClass('active');}}});});